name: csv2cmi
version: git
summary: CSV2CMI
description: |
  OfflineIMAP is software that downloads your email mailbox(es) as local
  Maildirs. OfflineIMAP will synchronize both sides via IMAP.

grade: devel
confinement: devmode

apps:
  csv2cmi:
    command: bin/csv2cmi

parts:
  csv2cmi:
    plugin: python
    source: .
