name: csv2cmi
version: git
summary: CSV2CMI
description: CSV2CMI is a little program to transform a table of letters (given as .csv) into the CMI format.
grade: stable
confinement: devmode

apps:
  csv2cmi:
    command: bin/csv2cmi

parts:
  csv2cmi:
    plugin: python
    source: .
